geo_doc_generator/geo_doc_generator/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from users.views import UserRegisterView, UserUpdateView


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("geodetic_work.urls")),
    path("register/", UserRegisterView.as_view(), name="register"),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="users/login.html"),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(template_name="users/logout.html"),
        name="logout",
    ),
    path(
        "updateuser/<int:pk>/",
        UserUpdateView.as_view(),
        name="updateuser",
    ),
    path("geodetictools/", include("geodetic_tools.urls")),
    path("geodetictechnicaldoc/", include("geodetic_technical_documentation.urls")),
    path("georestapi/", include("geo_rest_api.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geo_doc_generator/geo_rest_api/urls.py
from django.urls import path
from geo_rest_api.views import GeodeticWorkDeleteApiView, GeodeticWorkEditApiView

urlpatterns = [
    path(
        "workdeleteapi/<int:pk>",
        GeodeticWorkDeleteApiView.as_view(),
        name="geodetic-work-delete-api",
    ),
    path(
        "workeditapi/<int:pk>",
        GeodeticWorkEditApiView.as_view(),
        name="geodetic-work-edit-api",
    ),
]

geo_doc_generator/geodetic_work/urls.py
from django.urls import path
from geodetic_work.views.geodetic_work.views import (
    GeodeticWorkCreatView,
    GeodeticWorkDetailsView,
    GeodeticWorkEditView,
    GeodeticWorkHome,
    GeodeticWorkListView,
)
from geodetic_work.views.technical_desc.views import (
    TechnicalDescriptionCreateView,
    TechnicalDescriptionUpdateView,
)
from geodetic_work.views.comparision_map.views import (
    ComparisionMapCreateView,
    ComparisionMapUpdateView,
)
from geodetic_work.views.network_survey.views import (
    GeodeticNetworkSurveyCreateView,
    GeodeticNetworkSurveyUpdateView,
)
from geodetic_work.views.network_draft.views import (
    GeodeticNetworkDraftCreateView,
    GeodeticNetworkDraftUpdateView,
)
from geodetic_work.views.network_coordinates.views import (
    NetworkCoordinatesCreateView,
    NetworkCooridnatesUpdateView,
)
from geodetic_work.views.field_draft.views import (
    FieldDraftCreateView,
    FieldDraftUpdateView,
)
from geodetic_work.views.list_coordinates.views import (
    ListCoordinatesCreateView,
    ListCoordinatesUpdateView,
)
from geodetic_work.views.change_building.views import (
    ChangeBuildingCreateView,
    ChangeBuildingUpdateView,
    ChangeBuildingDeleteView,
)
from geodetic_work.views.change_plots.views import (
    ChangePlotsCreateView,
    ChangePlotsUpdateView,
)

urlpatterns = [
    path("", GeodeticWorkHome.as_view(), name="geodetic-work-home"),
    path("worklist/", GeodeticWorkListView.as_view(), name="geodetic-work-list"),
    path("workcreate/", GeodeticWorkCreatView.as_view(), name="geodetic-work-create"),
    path(
        "workdetails/<int:pk>",
        GeodeticWorkDetailsView.as_view(),
        name="geodetic-work-details",
    ),
    path(
        "workedit/<int:pk>", GeodeticWorkEditView.as_view(), name="geodetic-work-edit"
    ),
    path(
        "workdetails/<int:pk>/techdesccreate/",
        TechnicalDescriptionCreateView.as_view(),
        name="technical-description-create",
    ),
    path(
        "techdescedit/<int:pk>",
        TechnicalDescriptionUpdateView.as_view(),
        name="technical-description-edit",
    ),
    path(
        "workdetails/<int:pk>/comparisionmapcreate/",
        ComparisionMapCreateView.as_view(),
        name="comparision-map-create",
    ),
    path(
        "comparisionmapedit/<int:pk>",
        ComparisionMapUpdateView.as_view(),
        name="comparision-map-edit",
    ),
    path(
        "workdetails/<int:pk>/networksurveycreate/",
        GeodeticNetworkSurveyCreateView.as_view(),
        name="network-survey-create",
    ),
    path(
        "networksurveyedit/<int:pk>",
        GeodeticNetworkSurveyUpdateView.as_view(),
        name="network-survey-edit",
    ),
    path(
        "workdetails/<int:pk>/networkdraftcreate/",
        GeodeticNetworkDraftCreateView.as_view(),
        name="network-draft-create",
    ),
    path(
        "networkdraft/<int:pk>",
        GeodeticNetworkDraftUpdateView.as_view(),
        name="network-draft-edit",
    ),
    path(
        "workdetails/<int:pk>/networkcoordinatescreate/",
        NetworkCoordinatesCreateView.as_view(),
        name="network-coordinates-create",
    ),
    path(
        "networkcoordinates/<int:pk>",
        NetworkCooridnatesUpdateView.as_view(),
        name="network-coordinates-edit",
    ),
    path(
        "workdetails/<int:pk>/fielddraftcreate/",
        FieldDraftCreateView.as_view(),
        name="field-draft-create",
    ),
    path(
        "fielddraft/<int:pk>", FieldDraftUpdateView.as_view(), name="field-draft-edit"
    ),
    path(
        "workdetails/<int:pk>/listcoordinatescreate/",
        ListCoordinatesCreateView.as_view(),
        name="list-coordinates-create",
    ),
    path(
        "listcoordinates/<int:pk>",
        ListCoordinatesUpdateView.as_view(),
        name="list-coordinates-edit",
    ),
    path(
        "workdetails/<int:pk>/changebuildingscreate/",
        ChangeBuildingCreateView.as_view(),
        name="change-buildings-create",
    ),
    path(
        "changebuildings/<int:pk>",
        ChangeBuildingUpdateView.as_view(),
        name="change-buildings-edit",
    ),
    path(
        "deletebuildings/<int:pk>",
        ChangeBuildingDeleteView.as_view(),
        name="change-buildings-delete",
    ),
    path(
        "workdetails/<int:pk>/changeplotscreate/",
        ChangePlotsCreateView.as_view(),
        name="change-plots-create",
    ),
    path(
        "changeplots/<int:pk>",
        ChangePlotsUpdateView.as_view(),
        name="change-plots-edit",
    ),
]

geo_doc_generator/geodetic_work/models/geodetic_work.py
from django.db import models
from django.db.models.deletion import CASCADE
from django.utils.translation import gettext_lazy as _
from django.conf import settings
from django.utils import timezone

DOCUMENTS_PATH = "documents/"


def get_upload_path(instance, filename):
    """Generates the file path for the TDocuments."""
    return f"{DOCUMENTS_PATH}/{instance.id}/{filename}"


class GeodeticWork(models.Model):
    class Status(models.TextChoices):
        INPROGRESS = "INP", _("W trakcie")
        ENDED = "END", _("Zakończona")
        CANCELLED = "CAN", _("Anulowana")

    class WorkScope(models.TextChoices):
        MDCP = "MDCP", _("sporządzenie mapy do celów projektowych")
        INWENT = "INW", _("geodezyjna inwentaryzacja powykonawcza obiektów budowalnych")
        WZNOW = "WZNOW", _(
            "wznowienie znaków granicznych, wyznaczenie pkt granicznych lub ustalenie przebiegu granic"
        )
        MZPPN = "MZPPN", _("sporządzenie mapy z projektem podziału nieruchomości")
        PSCPN = "PSCPN", _("sporządzenie projeku scalenia i podziału nieruchomości")
        MDCPRAW = "MDCPRAW", _("sporządzenie innej mapy do celów prawnych")
        PSWG = "PSWG", _("sporządzenie projektu scalenia lub wymiany gruntów")
        ROZG = "ROZG", _(
            "sporządzenie dokumentacji geodezyjnej na potrzeby rozgranicznenia nieruchomości"
        )
        INNE = "INNE", _("wykonanie innych czynności lub dokumentacji geodezyjnej")

    id_work = models.CharField(
        "identyfikator pracy", max_length=25, null=False, default="XX.6640.XXXX.RRRR"
    )
    voivodeship = models.CharField(
        "województwo", max_length=50, null=True, default="zachodniopomorskie"
    )
    county = models.CharField("powiat", max_length=50, null=True)
    commune = models.CharField("gmina", max_length=50, null=True)
    precinct = models.CharField("obręb", max_length=50, null=True)
    work_object = models.CharField("obiekt", max_length=100, null=True)
    plots = models.CharField("działki", max_length=50, null=True)
    work_scope = models.CharField(
        "cel pracy",
        max_length=10,
        null=True,
        choices=WorkScope.choices,
        default=WorkScope.MDCP,
    )
    survey_date = models.DateField(
        "data pomiaru", blank=True, null=True, default=timezone.now
    )
    begin_date = models.DateField(
        "data rozpoczęcia", blank=True, null=True, default=timezone.now
    )
    area = models.CharField("obszar", max_length=10, null=True)
    change_bdot_database = models.BooleanField(
        "zmiana BDOT500", default=False, null=True
    )
    change_gesut_database = models.BooleanField(
        "zmiana GESUT", default=False, null=True
    )
    change_egib_database = models.BooleanField("zmiana EGiB", default=False, null=True)
    documentation_date = models.DateField(
        "data dokumentacji", default=timezone.now, blank=True, null=True
    )
    contractor = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=1, editable=False
    )

    status = models.CharField(
        "status",
        max_length=3,
        null=True,
        choices=Status.choices,
        default=Status.INPROGRESS,
    )
    pdf_documentation = models.FileField(
        upload_to=get_upload_path, null=True, blank=True
    )

    def __str__(self) -> str:
        return f"{self.id_work} - {self.work_object}"

geo_doc_generator/geodetic_work/forms.py
from django import forms

geo_doc_generator/geodetic_technical_documentation/views/list_coordinates/views.py
from io import BytesIO
from django.http import Http404, HttpResponse
from django.shortcuts import render
from django.template.loader import get_template
from django.views.generic import DetailView
from django.views.generic.edit import FormMixin
from django.core.files import File
from geodetic_work.models.document import *
from geodetic_work.models.geodetic_work import GeodeticWork
from geodetic_technical_documentation.serializers import GeodeticWorkDocumentsSerializer
from geodetic_technical_documentation.utilis.utilis import DocumentPreview, DeleteOldPDF
from xhtml2pdf import pisa
from PyPDF2 import PdfReader, PdfMerger
from django.conf import settings


class ListOfCoordinatesGeneratePDF(DetailView):
    model = GeodeticWork

    def save_pdf_to_file(self, pdf_file):
        self.object = self.get_object()
        list_of_coordinates = ListOfCoordinates.objects.get(id_work=self.object.id)
        filename = f"{self.object.id_work}_list_coord.pdf"
        try:
            DeleteOldPDF._delete_file(list_of_coordinates.pdf_file.path)
        except ValueError:
            pass
        with open(filename, "wb+") as file:
            file.write(pdf_file)
            list_of_coordinates.pdf_file = File(file, filename)
            list_of_coordinates.save()
        return pdf_file

    def get_geodetic_work_context(self, instance):
        pdf_context = dict()
        geodetic_work_serializer = GeodeticWorkDocumentsSerializer(instance)
        pdf_context = geodetic_work_serializer.serialize()
        return pdf_context

    def generate_pdf(self, template_src, context_dict=None):
        if context_dict is None:
            context_dict = {}
        template = get_template(template_src)
        html = template.render(context_dict)
        buffer = BytesIO()
        status = pisa.CreatePDF(BytesIO(html.encode("utf-8")), buffer, encoding="utf-8")
        buffer.seek(0)
        pdf_file = buffer.read()
        if not status.err:
            return self.save_pdf_to_file(pdf_file)

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        pdf_contex = self.get_geodetic_work_context(self.object)
        pdf_generation = self.generate_pdf(
            "geodetic_work/list_coordinates.html", pdf_contex
        )
        response = HttpResponse(pdf_generation, content_type="application/pdf")
        filename = f"Wykaz_wsp_{self.object.id_work}.pdf"
        content = f"inline; filename={filename}"
        response["Content-Disposition"] = content
        return response


class ListOfCoordinatesGeneratePdfPreview(DocumentPreview):
    template_name = "geodetic_work/list_coordinates.html"

geo_doc_generator/geodetic_work/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.views.generic import ListView, CreateView, DetailView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from geodetic_work.models.geodetic_work import GeodeticWork


class GeodeticWorkHome(ListView, LoginRequiredMixin, UserPassesTestMixin):
    model = GeodeticWork
    template_name = "geodetic_work/geodetic_work_home.html"
    context_object_name = "works"
    queryset = GeodeticWork.objects.all()[:5]

    def test_func(self):
        geodetic_work = self.get_object()
        return self.request.user == geodetic_work.contractor


class GeodeticWorkListView(ListView, LoginRequiredMixin, UserPassesTestMixin):
    model = GeodeticWork
    template_name = "geodetic_work/geodetic_work_list.html"
    context_object_name = "works"
    ordering = ["-begin_date"]
    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()
        search_query = self.request.GET.get("search", None)
        if search_query:
            queryset = queryset.filter(
                id_work__icontains=search_query
            ) | queryset.filter(work_object__icontains=search_query)
        return queryset

    def test_func(self):
        geodetic_work = self.get_object()
        return self.request.user == geodetic_work.contractor


class GeodeticWorkCreatView(CreateView, LoginRequiredMixin, UserPassesTestMixin):
    model = GeodeticWork
    template_name = "geodetic_work/geodetic_work_create.html"
    success_url = "geodetic-work-home"
    fields = "__all__"

    def form_valid(self, form):
        work_id = form.data.get("id_work")
        form.save()
        messages.success(self.request, f"Dodałeś nową pracę o id: {work_id} ")
        return redirect(self.success_url)

    def test_func(self):
        geodetic_work = self.get_object()
        return self.request.user == geodetic_work.contractor


class GeodeticWorkDetailsView(DetailView, LoginRequiredMixin, UserPassesTestMixin):
    model = GeodeticWork
    template_name = "geodetic_work/geodetic_work_details.html"
    context_object_name = "work"

    def test_func(self):
        geodetic_work = self.get_object()
        return self.request.user == geodetic_work.contractor


class GeodeticWorkEditView(UpdateView, LoginRequiredMixin, UserPassesTestMixin):
    model = GeodeticWork
    template_name = "geodetic_work/geodetic_work_edit.html"
    context_object_name = "work"
    success_url = "geodetic-work-home"
    fields = "__all__"

    def form_valid(self, form):
        work_id = form.data.get("id_work")
        form.save()
        messages.success(self.request, f"Zaaktualizowałeś dane pracy o id: {work_id} ")
        return redirect(self.success_url)

    def test_func(self):
        geodetic_work = self.get_object()
        return self.request.user == geodetic_work.contractor

geo_doc_generator/geodetic_work/views/change_building/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from geodetic_work.models.geodetic_work import GeodeticWork
from geodetic_work.models.document import *


class ChangeBuildingCreateView(CreateView, LoginRequiredMixin, UserPassesTestMixin):
    model = ChangeListBuilding
    template_name = "geodetic_work/document_create.html"
    fields = "__all__"

    def get_initial(self):
        work_id = get_object_or_404(GeodeticWork, id=self.kwargs["pk"])
        initial = {"id_work": work_id}
        return initial

    def form_valid(self, form):
        work_id = form.data.get("id_work")
        form.save()
        messages.success(
            self.request,
            "Dodałeś dokument: Wykaz zmian danych ewidencyjnych dot. budynku",
        )
        return redirect("geodetic-work-details", work_id)

    def test_func(self):
        geodetic_work = self.get_object()
        return self.request.user == geodetic_work.contractor

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["geodetic_work"] = get_object_or_404(GeodeticWork, id=self.kwargs["pk"])
        return context


class ChangeBuildingUpdateView(UpdateView, LoginRequiredMixin, UserPassesTestMixin):
    model = ChangeListBuilding
    template_name = "geodetic_work/document_create.html"
    fields = "__all__"

    def form_valid(self, form):
        work_id = form.data.get("id_work")
        form.save()
        messages.success(
            self.request,
            "Zmieniłeś dane dokumentu: Wykaz zmian danych ewidencyjnych dot. budynku",
        )
        return redirect("geodetic-work-details", work_id)

    def test_func(self):
        geodetic_work = self.get_object()
        return self.request.user == geodetic_work.contractor


class ChangeBuildingDeleteView(UserPassesTestMixin, DeleteView):
    model = ChangeListBuilding
    template_name = "geodetic_work/document_delete.html"

    def test_func(self):
        geodetic_work = self.get_object()
        return self.request.user == geodetic_work.contractor

geo_doc_generator/geodetic_work/templates/geodetic_work/document_create.html
{% extends 'geodetic_work/base.html' %}
{% block content %}
{% load crispy_forms_tags %}
{% if user.is_authenticated %}


<div class="content-section">
    <form method="POST" enctype = "multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Wprowadź dane dokumentu:</legend>
            <small class="text-muted">
                {{ geodetic_work }}
            </small>
            {{ form|crispy }}
        </fieldset>
        <div>
            <button class="btn btn-outline-info" type="submit">Zapisz</button>
        </div>
    </form>
</div>


{% else %}
<div class="content-section">
    <h2>Nie jesteś zalogowany</h2>
    <div class="border-top pt-3">
        <small class="text-muted">
            <a  href="{% url 'login' %}">Zaloguj się</a>
        </small>
    </div>
</div>
{% endif %}
{% endblock %}

geo_doc_generator/geodetic_work/templates/geodetic_work/geodetic_work_details.html
{% extends 'geodetic_work/base.html' %}
{% load static %}
{% block js %}
    <script src="{% static 'geodetic_work/js/geodetic_work_home.js' %}"></script>
{% endblock %}
{% block content %}
{% if user.is_authenticated %}
    <h3>Praca o identyfikatorze: {{work.id_work}}</h3>
    <h4>Obiekt: {{work.work_object}}</h4>
    <table>
        <tr><th>ID pracy</th><th>status</th><th>woj.</th><th>powiat</th>
        <th>jednostka ew.</th><th>obręb</th><th>obiekt</th><th>działki</th><th>cel</th>
        <th>data aktual.</th><th>data operatu</th><th>data mat.</th><th>obszar[ha]</th>
        <th>zmiany BDOT500</th><th>zmiany GESUT</th><th>zmiany EGiB</th>
        </tr>
            <tr>
                <td>{{ work.id_work }}</td>
                <td>{{ work.get_status_display }}</td>
                <td>{{work.voivodeship}}</td>
                <td>{{work.county}}</td>
                <td>{{work.commune}}</td>
                <td>{{work.precinct}}</td>
                <td>{{work.work_object}}</td>
                <td>{{work.plots}}</td>
                <td>{{ work.get_work_scope_display }}</td>
                <td>{{work.survey_date}}</td>
                <td>{{work.documentation_date}}</td>
                <td>{{work.begin_date}}</td>
                <td>{{work.change_bdot_database}}</td>
                <td>{{work.change_gesut_database}}</td>
                <td>{{work.change_egib_database}}</td>
                <td>
                    <form>
                        <button type="submit" formaction="{% url 'geodetic-work-edit' work.id %}">Edytuj</button>
                    </form>
                </td>
                <td><button id="delete-work-{{ work.id }}" onClick="deleteWork(this.id)">Usuń</button></td>
            </tr>
        </table>
        <BR>
        <h4>Dokumenty do operatu:</h4>
        <h5><a href="{% url 'geo-doc-pdf-generator' work.id %}">GENERUJ ZBIORCZY PLIK PDF</a></h5>
        <table>
                <tr><th>l. p.</th><th>zawartość</th><th>status</th><th>Edycja</th><th>PDF</th>
                </tr>
                <tr>
                    <td>1.</td>
                    <td>Spis Treści</td>
                    <td><a href="{% url 'table-of-content-preview' work.id %}">Podgląd</a></td>
                    <td><a href="{% url 'table-of-content-generate' work.id %}">Generuj</a></td>
                </tr>
                <tr>
                    <td>2.</td>
                    <td>Sprawozdanie techniczne</td>
                    {% if work.technicaldescription.id %}
                    <td>
                     <a href="{% url 'technical-discription-preview' work.id %}">Podgląd</a>
                    </td>
                    <td><a href="{% url 'technical-description-edit' work.technicaldescription.id %}">Edytuj</a>
                    </td>
                    <td> <a href="{% url 'technical-discription-generate' work.id %}">Generuj PDF</a>
                        <a href="{% url 'docx-technical-description-generate' work.id %}">Generuj DOCX</a>
                    </td>
                        {% else %}
                        <td>Nie utworzono</td>
                        <td><a href="{% url 'technical-description-create' work.id %}">Dodaj</a></td>
                        {% endif %}
                    </td>

                </tr>
                <tr>
                    <td>3.</td>
                    <td>Mapa porównania z terenem</td>
                    {% if work.comaparisionmap.id %}
                    <td>
                        <a href="{% url 'comparision-map-edit' work.comaparisionmap.id %}">Podgląd</a>
                    </td>
                    <td>
                        <a href="{% url 'comparision-map-edit' work.comaparisionmap.id %}">Edytuj</a>
                    </td>

                    {% else %}
                    <td>Nie utworzono</td>
                    <td>
                        <a href="{% url 'comparision-map-create' work.id %}">Dodaj</a>
                    </td>
                    {% endif %}
                </tr>
                <tr>
                    <td>4.</td>
                    <td>Dane obserwacyjne osnowy pomiarowej</td>
                    {% if work.geodeticnetworksurveydata.id %}
                    <td>
                        <a href="{% url 'network-survey-preview' work.id %}">Podgląd</a>
                    </td>
                    <td>
                        <a href="{% url 'network-survey-edit' work.geodeticnetworksurveydata.id %}">Edytuj</a>
                    </td>
                    <td> <a href="{% url 'network-survey-generate' work.id %}">Generuj PDF</a></td>
                    {% else %}
                    <td>Nie utworzono</td>
                    <td>
                        <a href="{% url 'network-survey-create' work.id %}">Dodaj</a>
                    </td>
                    {% endif %}
                </tr>
                <tr>
                    <td>5.</td>
                    <td>Szkic osnowy pomiarowej</td>
                         {% if work.geodeticnetworkdraft.id %}
                        <td>
                            <a href="{% url 'network-draft-edit' work.geodeticnetworkdraft.id %}">Podgląd</a>
                        </td>
                        <td>
                            <a href="{% url 'network-draft-edit' work.geodeticnetworkdraft.id %}">Edytuj</a>
                        </td>
                        {% else %}
                        <td>Nie utworzono</td>
                        <td>
                            <a href="{% url 'network-draft-create' work.id %}">Dodaj</a>
                        </td>
                        {% endif %}
                </tr>
                <tr>
                    <td>6.</td>
                    <td>Wykaz współrzędnych osnowy pomiarowej</td>
                        {% if work.geodeticnetworkcoordinates.id %}
                        <td>
                            <a href="{% url 'network-coordinates-preview' work.id %}">Podgląd</a>
                        </td>
                        <td>
                            <a href="{% url 'network-coordinates-edit' work.geodeticnetworkcoordinates.id %}">Edytuj</a>
                        </td>
                        <td> <a href="{% url 'network-coordinates-generate' work.id %}">Generuj PDF</a></td>
                        {% else %}
                        <td>Nie utworzono</td>
                        <td>
                            <a href="{% url 'network-coordinates-create' work.id %}">Dodaj</a>
                        </td>
                        {% endif %}
                </tr>
                <tr>
                    <td>7.</td>
                    <td>Szkice polowe</td>
                        {% if work.fielddraft.id %}
                        <td>
                            <a href="{% url 'field-draft-edit' work.fielddraft.id %}">Podgląd</a>
                        </td>
                        <td>
                            <a href="{% url 'field-draft-edit' work.fielddraft.id %}">Edytuj</a>
                        </td>
                        {% else %}
                        <td>Nie utworzono</td>
                        <td>
                            <a href="{% url 'field-draft-create' work.id %}">Dodaj</a>
                        </td>
                        {% endif %}
                </tr>
                <tr>
                    <td>8.</td>
                    <td>Wykaz współrzędnych punktów pomierzonych</td>
                        {% if work.listofcoordinates.id %}
                        <td>
                            <a href="{% url 'list-coordinates-preview' work.id %}">Podgląd</a>
                        </td>
                        <td>
                            <a href="{% url 'list-coordinates-edit' work.listofcoordinates.id %}">Edytuj</a>
                        </td>
                        <td> <a href="{% url 'list-coordinates-generate' work.id %}">Generuj PDF</a></td>
                        {% else %}
                        <td>Nie utworzono</td>
                        <td>
                            <a href="{% url 'list-coordinates-create' work.id %}">Dodaj</a>
                        </td>
                        {% endif %}
                </tr>
                <tr>
                    <td>9.</td>
                    <td>Wykaz zmian danych ewidenycyjnych dot. budynków</td>
                        {% if work.changelistbuilding.id %}
                        <td>
                            <a href="{% url 'change-buildings-edit' work.changelistbuilding.id %}">Podgląd</a>
                        </td>
                        <td>
                            <a href="{% url 'change-buildings-edit' work.changelistbuilding.id %}">Edytuj</a>
                        </td>
                        {% else %}
                        <td>Nie utworzono</td>
                        <td>
                            <a href="{% url 'change-buildings-create' work.id %}">Dodaj</a>
                        </td>
                        {% endif %}
                </tr>
                <tr>
                    <td>10.</td>
                    <td>Wykaz zmian danych ewidenycyjnych dot. działek</td>
                        {% if work.changelistplot.id %}
                        <td>
                            <a href="{% url 'change-plots-edit' work.changelistplot.id %}">Podgląd</a>
                        </td>
                        <td>
                            <a href="{% url 'change-plots-edit' work.changelistplot.id %}">Edytuj</a>
                        </td>
                        {% else %}
                        <td>Nie utworzono</td>
                        <td>
                            <a href="{% url 'change-plots-create' work.id %}">Dodaj</a>
                        </td>
                        {% endif %}
                </tr>
        </table>


{% else %}
<div class="content-section">
    <h2>Nie jesteś zalogowany</h2>
    <div class="border-top pt-3">
        <small class="text-muted">
            <a  href="{% url 'login' %}">Zaloguj się</a>
        </small>
    </div>
</div>
{% endif %}
{% endblock %}